name: Build Debezium

on:
  push:
    branches:
      - voyager-main
  pull_request:
    branches:
      - voyager-main

jobs:
  build_debezium_server:
    name: "Build Debezium Server"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-debezium-test-build-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-debezium-test-build-${{ hashFiles('**/pom.xml') }}
      - name: Push dist name
        if : ${{ github.event_name == 'push' }}
        run: |
          echo "DIST_NAME=debezium-server-latest" >> "$GITHUB_ENV"
      - name: Branch Dist name
        if : ${{ github.event_name == 'pull_request' }}
        run: |
          echo "DIST_NAME=debezium-server-${GITHUB_HEAD_REF//\//_}" >> "$GITHUB_ENV"
      - name: Build Debezium Server
        run: |
          sh buildDebeziumServer.sh
          mv debezium-server/debezium-server-dist/target/debezium-server-dist-2.2.0-SNAPSHOT.tar.gz "debezium-server/debezium-server-dist/target/${DIST_NAME}.tar.gz"
#      - name: Upload Release Asset
#        id: upload-release-asset
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ github.token }}
#        with:
#          upload_url: https://uploads.github.com/repos/yugabyte/debezium/releases/102178405/assets{?name,label}
#          asset_path: debezium-server/debezium-server-dist/target/${{ env.DIST_NAME }}.tar.gz
#          asset_name: ${{ env.DIST_NAME }}.tar.gz
#          asset_content_type: application/zip
#      - name: Publish to voyager-debezium
#        uses: softprops/action-gh-release@v1
#        with:
#          prerelease: true
#          tag_name: voyager-debezium
#          files: debezium-server/debezium-server-dist/target/${{ env.DIST_NAME }}.tar.gz
#          target_commitish: ${{ github.sha }}
      - name: Publish to voyager-debezium
        run: |
          gh release upload voyager-debezium debezium-server/debezium-server-dist/target/${{ env.DIST_NAME }}.tar.gz --clobber
        env:
          GITHUB_TOKEN: ${{ github.token }}
