name: Build Debezium

on:
  push:
    branches:
      - voyager-main
  pull_request:
    branches:
      - voyager-main

jobs:
  build_debezium_server:
    name: "Build Debezium Server"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-debezium-test-build-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-debezium-test-build-${{ hashFiles('**/pom.xml') }}

      - name: Build Debezium Server
        run: |
          sh buildDebeziumServer.sh
          mv debezium-server/debezium-server-dist/target/debezium-server-dist-2.2.0-SNAPSHOT.tar.gz debezium-server/debezium-server-dist/target/debezium-server-latest.tar.gz
      - name: Publish to voyager-debezium-latest
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: voyager-debezium-latest
          files: debezium-server/debezium-server-dist/target/debezium-server-latest.tar.gz
          target_commitish: ${{ github.sha }}
