name: Build Debezium Server Release

on:
  push:
    tags:
      - 'voyager-v*.*.*'

jobs:
  create_release:
    name: "Create Release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Compute release variables (rel)
        run: |
          RELEASE_VERSION=$(echo $GITHUB_REF | cut -d / -f 3 | sed 's/voyager-//')
          raw_branch=$(git branch -r --contains $GITHUB_REF)
          BRANCH_NAME=$(echo $raw_branch | cut -d / -f 2 | sed 's/voyager-rel-//')
          echo "DIST_NAME=debezium-server-${RELEASE_VERSION}" >> "$GITHUB_OUTPUT" 
          echo "RELEASE_NAME=voyager-debezium-${BRANCH_NAME}" >> "$GITHUB_OUTPUT"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.RELEASE_NAME }}
          release_name: ${{ env.RELEASE_NAME }}

  build_debezium_server:
    - name: Build and Package Debezium Server
      needs: [create_release]
      runs-on: ubuntu-latest
      uses: ./.github/workflows/voyager-debezium-build-release.yml
      with:
        dist_name: ${{ needs.create_release.outputs.DIST_NAME }}
        release_name: ${{ needs.create_release.outputs.RELEASE_NAME }}

