name: Build Debezium Server Main

on:
  push:
    branches:
      - voyager-main

jobs:
  build_debezium_server:
    name: "Build Debezium Server PR"
    runs-on: ubuntu-latest
    steps:
      - name: Compute dist name (push) # debezium-server-latest in case it is a push to voyager-main
        run: |
          echo "DIST_NAME=debezium-server-latest" >> "$GITHUB_ENV"
          echo "RELEASE_NAME=voyager-debezium" >> "$GITHUB_ENV"
      - name: Build and Package Debezium Server
        uses: yugabyte/debezium/.github/workflows/voyager-debezium-build-release.yml
        with:
          dist_name: ${{ env.DIST_NAME }}
          release_name: ${{ env.RELEASE_NAME }}

