name: Testing

on:
  push:
    branches:
      - ybdb-debezium-2.5.2
  pull_request:
    branches:
      - ybdb-debezium-2.5.2

env:
  YUGABYTEDB_VERSION: 2024.1.0.0-b19

jobs:
  build:
    name: Build and run PG tests
    runs-on: ubuntu-latest
    steps:
      - name: Download YugabyteDB
        uses: wei/wget@v1
        with:
          args: -O yugabytedb-linux.tar.gz https://downloads.yugabyte.com/releases/2024.1.0.0/yugabyte-2024.1.0.0-b129-linux-x86_64.tar.gz
      - name: Extract YugabyteDB package
        uses: a7ul/tar-action@v1.2.0
        id: extract
        with:
          command: x
          cwd: ./
          files: yugabytedb-linux.tar.gz
          outPath: ./
      - name: Complete post install actions for YugabyteDB
        run: ./yugabyte-2024.1.0.0/bin/post_install.sh
      - name: Start yugabyted
        run: >
          ./yugabyte-2024.1.0.0/bin/yugabyted start
          --advertise_address 127.0.0.1 --ui=false
          --master_flags="yb_enable_cdc_consistent_snapshot_streams=true,allowed_preview_flags_csv={yb_enable_cdc_consistent_snapshot_streams,ysql_yb_enable_replication_commands,ysql_yb_enable_replica_identity},ysql_yb_enable_replica_identity=true,ysql_yb_enable_replication_commands=true,ysql_TEST_enable_replication_slot_consumption=true"
          --tserver_flags="allowed_preview_flags_csv={yb_enable_cdc_consistent_snapshot_streams,ysql_yb_enable_replication_commands,ysql_yb_enable_replica_identity,cdcsdk_enable_dynamic_table_support},cdcsdk_enable_dynamic_table_support=true,ysql_yb_enable_replica_identity=true,ysql_yb_enable_replication_commands=true,yb_enable_cdc_consistent_snapshot_streams=true,ysql_TEST_enable_replication_slot_consumption=true,ysql_cdc_active_replication_slot_window_ms=0,ysql_sequence_cache_method=server,cdcsdk_publication_list_refresh_interval_secs=3"
      - name: Checkout Action
        uses: actions/checkout@v4
      
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      
      - name: Download dependencies
        run: ./mvnw clean install -Dquick -pl debezium-connector-postgres -am