name: Publish YugabyteDBConnector image to Quay

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the connector to be released"
        required: true
        type: string
      isSnapshotBuild:
        description: "Consider this build as a snapshot build"
        required: true
        type: boolean
        default: true

jobs:
  build:
    name: "Build PG connector"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v4
      
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      
      - name: Download dependencies
        run: ./mvnw clean install -Dquick -pl debezium-connector-postgres -am
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_BOT_USERNAME }}
          password: ${{ secrets.QUAY_BOT_TOKEN }}
      - name: Build docker image
        run: docker build . -t quay.io/yugabyte/ybdb-debezium:${{ inputs.version }} --platform linux/amd64
      - name: Push image to Quay
        run: docker push ${{ inputs.version }}